Name: Cake.MkDocs
NuGet: Cake.MkDocs
Assemblies:
- "/**/Cake.MkDocs.dll"
- "/**/Semver.dll"
Repository: https://github.com/michalkowal/Cake.MkDocs/
Author: Michał Kowal
Description: "Cake Addin that extends Cake with ability to run the MkDocs."
Categories:
- MkDocs
- Documentation
- Static Site Generation
