# Build script
init:
  - git config --global core.autocrlf true

# Build script
build_script:
  - cmd: localdeploy.cmd

# Tests
test: off

# Artifacts
artifacts:
# Static website
  - path: LocalDeploy

# Branches to build
branches:
  # Whitelist
  only:
    - develop
    - master